# Generated by Django 6.0.7 on 2026-07-30 03:19

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ['-is_active', 'name']},
        ),
        migrations.AddField(
            model_name='account',
            name='account_number',
            field=models.CharField(blank=True, help_text='Masked for security — only last 4 digits displayed', max_length=100),
        ),
        migrations.AddField(
            model_name='account',
            name='credit_limit',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Credit limit for credit card accounts', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='account',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollar (USD)'), ('EUR', 'Euro (EUR)'), ('GBP', 'British Pound (GBP)'), ('JPY', 'Japanese Yen (JPY)'), ('CAD', 'Canadian Dollar (CAD)'), ('AUD', 'Australian Dollar (AUD)'), ('CHF', 'Swiss Franc (CHF)'), ('CNY', 'Chinese Yuan (CNY)'), ('INR', 'Indian Rupee (INR)')], default='USD', max_length=3),
        ),
        migrations.AddField(
            model_name='account',
            name='include_in_totals',
            field=models.BooleanField(default=True, help_text='Include in net worth and total calculations'),
        ),
        migrations.AddField(
            model_name='account',
            name='institution',
            field=models.CharField(blank=True, help_text='Bank or financial institution name', max_length=100),
        ),
        migrations.AddField(
            model_name='account',
            name='interest_rate',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='APY percentage (e.g. 2.500 for 2.5%)', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))]),
        ),
        migrations.AddField(
            model_name='account',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Inactive accounts are hidden from lists'),
        ),
        migrations.AddField(
            model_name='account',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='account',
            name='opened_date',
            field=models.DateField(blank=True, help_text='When the account was opened', null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='routing_number',
            field=models.CharField(blank=True, help_text='ABA routing number (US accounts)', max_length=9),
        ),
        migrations.AddField(
            model_name='account',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('checking', 'Checking'), ('savings', 'Savings'), ('credit_card', 'Credit Card'), ('cash', 'Cash'), ('investment', 'Investment'), ('loan', 'Loan'), ('other', 'Other')], max_length=20),
        ),
    ]
