# Generated by Django 6.0.7 on 2026-07-30 03:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_account_options_account_account_number_and_more'),
        ('categories', '0002_alter_category_options_category_color_and_more'),
        ('transactions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-date', '-created_at']},
        ),
        migrations.AddField(
            model_name='transaction',
            name='is_reconciled',
            field=models.BooleanField(default=False, help_text='Whether this transaction has been reconciled with a bank statement'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='is_recurring',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transaction',
            name='memo',
            field=models.CharField(blank=True, help_text='Bank memo or additional details', max_length=255),
        ),
        migrations.AddField(
            model_name='transaction',
            name='notes',
            field=models.TextField(blank=True, help_text='Free-form notes'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='payee',
            field=models.CharField(blank=True, help_text='Who the money went to or came from', max_length=100),
        ),
        migrations.AddField(
            model_name='transaction',
            name='pending',
            field=models.BooleanField(default=False, help_text='Whether this transaction is still pending (not yet settled)'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='reconciled_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='recurring_ends',
            field=models.DateField(blank=True, help_text='Date when recurring transaction ends', null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='recurring_frequency',
            field=models.CharField(blank=True, choices=[('weekly', 'Weekly'), ('biweekly', 'Bi-weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annually', 'Annually')], max_length=10),
        ),
        migrations.AddField(
            model_name='transaction',
            name='reference_number',
            field=models.CharField(blank=True, help_text='Check number, bank transaction ID, or other reference', max_length=100),
        ),
        migrations.AddField(
            model_name='transaction',
            name='tags',
            field=models.CharField(blank=True, help_text='Comma-separated tags for flexible categorization', max_length=255),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(blank=True, choices=[('income', 'Income'), ('expense', 'Expense'), ('transfer', 'Transfer')], help_text='Derived from category type but set explicitly for filtering', max_length=10),
        ),
        migrations.AddField(
            model_name='transaction',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', 'date'], name='transaction_user_id_8af7f1_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', 'account', 'date'], name='transaction_user_id_73de81_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', 'is_reconciled'], name='transaction_user_id_335e28_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', 'pending'], name='transaction_user_id_32bb3c_idx'),
        ),
    ]
