# Generated by Django 6.0.7 on 2026-08-02 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_normalize_amount_signs'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='external_id',
            field=models.CharField(blank=True, help_text='Stable id from a bank feed (dedup key)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='source',
            field=models.CharField(blank=True, help_text='How the transaction entered the system (manual, bank_sync, import)', max_length=20),
        ),
    ]
