# Generated by Django 6.0.7 on 2026-07-30 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='budget_warnings',
            field=models.BooleanField(default=True, help_text='Receive budget warning notifications'),
        ),
        migrations.AddField(
            model_name='profile',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollar (USD)'), ('EUR', 'Euro (EUR)'), ('GBP', 'British Pound (GBP)'), ('JPY', 'Japanese Yen (JPY)'), ('CAD', 'Canadian Dollar (CAD)'), ('AUD', 'Australian Dollar (AUD)'), ('CHF', 'Swiss Franc (CHF)'), ('CNY', 'Chinese Yuan (CNY)'), ('INR', 'Indian Rupee (INR)')], default='USD', max_length=3),
        ),
        migrations.AddField(
            model_name='profile',
            name='date_format',
            field=models.CharField(choices=[('%Y-%m-%d', 'YYYY-MM-DD (2025-01-15)'), ('%m/%d/%Y', 'MM/DD/YYYY (01/15/2025)'), ('%d/%m/%Y', 'DD/MM/YYYY (15/01/2025)'), ('%d-%b-%Y', 'DD Mon YYYY (15 Jan 2025)')], default='%Y-%m-%d', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='email_notifications',
            field=models.BooleanField(default=True, help_text='Receive email notifications'),
        ),
        migrations.AddField(
            model_name='profile',
            name='first_day_of_month',
            field=models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (24, 24), (25, 25), (26, 26), (27, 27), (28, 28), (29, 29), (30, 30), (31, 31)], default=1),
        ),
        migrations.AddField(
            model_name='profile',
            name='first_day_of_week',
            field=models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7)], default=1),
        ),
        migrations.AddField(
            model_name='profile',
            name='number_format',
            field=models.CharField(choices=[('en_US', '1,234.56 (US/UK style)'), ('de_DE', '1.234,56 (European style)'), ('fr_FR', '1 234,56 (French style)')], default='en_US', max_length=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='timezone',
            field=models.CharField(choices=[('UTC', 'UTC'), ('America/New_York', 'Eastern Time (US & Canada)'), ('America/Chicago', 'Central Time (US & Canada)'), ('America/Denver', 'Mountain Time (US & Canada)'), ('America/Los_Angeles', 'Pacific Time (US & Canada)'), ('Europe/London', 'London'), ('Europe/Paris', 'Paris'), ('Europe/Berlin', 'Berlin'), ('Asia/Tokyo', 'Tokyo'), ('Asia/Shanghai', 'Shanghai'), ('Asia/Kolkata', 'Kolkata'), ('Australia/Sydney', 'Sydney')], default='UTC', max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='transaction_reminders',
            field=models.BooleanField(default=False, help_text='Send reminders for pending transactions'),
        ),
        migrations.AddField(
            model_name='profile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
