# Generated by Django 6.0.7 on 2026-07-30 03:19

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='budget',
            options={'ordering': ['-month', 'category__name']},
        ),
        migrations.AddField(
            model_name='budget',
            name='budget_type',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('annual', 'Annual'), ('rolling', 'Rolling (custom period)')], default='monthly', max_length=10),
        ),
        migrations.AddField(
            model_name='budget',
            name='carried_over',
            field=models.BooleanField(default=False, help_text='Whether unused budget carries over to the next period'),
        ),
        migrations.AddField(
            model_name='budget',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='budget',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Inactive budgets are excluded from calculations'),
        ),
        migrations.AddField(
            model_name='budget',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='budget',
            name='period_end',
            field=models.DateField(blank=True, help_text='Actual end date of the budget period', null=True),
        ),
        migrations.AddField(
            model_name='budget',
            name='period_start',
            field=models.DateField(blank=True, help_text='Actual start date of the budget period', null=True),
        ),
        migrations.AddField(
            model_name='budget',
            name='rollover_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Amount carried over from the previous period', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='budget',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='budget',
            name='warning_threshold',
            field=models.DecimalField(decimal_places=2, default=80.0, help_text='Percentage of budget at which to show a warning (e.g. 80.00 for 80%)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))]),
        ),
        migrations.AlterField(
            model_name='budget',
            name='month',
            field=models.DateField(help_text='First day of the budget period'),
        ),
    ]
